- name: Install Packages
  yum:
    name:
      - httpd
      - php
      - policycoreutils-python
    state: latest

- name: Allow httpd to listen on TCP port 8888
  seport:
    ports: "{{ httpd_port }}"
    proto: tcp
    setype: http_port_t
    state: present

- name: Copy httpd.conf Template
  template:
    src: templates/httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0644
    setype: httpd_config_t

- name: Copy Ignition PHP Script
  copy:
    src: files/ignition-downloader.php
    dest: /var/www/html/ignition-downloader.php
    owner: root
    group: root
    mode: 0644
    setype: httpd_sys_content_t

# pull installer and oc client images
- name: Downloading OCP4 client
  get_url:
    url: "{{ ocp_client }}"
    dest: /usr/local/src/openshift-client-linux.tar.gz

- name: Downloading OCP4 Installer
  get_url:
    url: "{{ ocp_installer }}"
    dest: /usr/local/src/openshift-install-linux.tar.gz

- name: Unarchiving OCP4 client
  unarchive:
    src: /usr/local/src/openshift-client-linux.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Unarchiving OCP4 Installer
  unarchive:
    src: /usr/local/src/openshift-install-linux.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Removing files that are not needed
  file:
    path: /usr/local/bin/README.md
    state: absent

- name: Copy install-config.yaml template
  template:
    src: templates/install-config.yaml.j2
    dest: /root/ocp4/install-config.yaml

- name: Generate ignition configs
  shell: "openshift-install create ignition-configs --dir=/root/ocp4"

- name: Copy Ingition configs to web server location
  shell: "cp /root/ocp4/*.ign /var/www/html/"

- name: Restore SELinux Contexts in Document Root
  shell: restorecon -R /var/www/html

- name: Enable/Start httpd Service
  systemd:
    name: httpd
    state: started
    enabled: yes

