- name: Delete VMs
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    cluster: "{{ vcenter_cluster }}"
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ item }}.{{ cluster_name }}.{{ base_domain }}"
    state: absent
    force: yes
  register: vmware_guest_results
  with_items:
    - "{{ groups[provision_group] }}" 
